cache: name
call_hooks: ''
compiled_sdfg_call_hooks: ''
compiler:
  allow_shadowing: true
  allow_view_arguments: false
  build_folder_mode: development
  build_type: RelWithDebInfo
  codegen_lineinfo: false
  codegen_state_struct_suffix: _state_t
  cpp_standard: '20'
  cpu:
    args: -std=c++14 -O3 -march=native -fPIC
    executable: ''
    libs: ''
    openmp_sections: false
  cuda:
    allow_implicit_memlet_to_map: true
    args: -Xcompiler -march=native --use_fast_math -Xcompiler -Wno-unused-parameter
    backend: auto
    block_size_lastdim_limit: 64
    block_size_limit: 1024
    cuda_arch: '60'
    default_block_size: 32,1,1
    dynamic_map_block_size: 128,1,1
    dynamic_map_fine_grained: true
    hip_arch: gfx906
    hip_args: -fPIC -O3 -ffast-math -Wno-unused-parameter
    libs: ''
    max_concurrent_streams: 0
    mempool_release_threshold: -1
    path: ''
    persistent_map_SM_fraction: 1.0
    persistent_map_occupancy: 2
    syncdebug: false
    thread_id_type: int32
  default_data_types: Python
  extra_cmake_args: ''
  format_code: false
  format_config_file: ''
  indentation_spaces: 4
  inline_sdfgs: false
  library_extension: so
  library_prefix: lib
  lineinfo: inspect
  linker:
    args: ''
    executable: ''
  max_stack_array_size: 65536
  mpi:
    executable: ''
  unique_functions: hash
  use_cache: false
debugprint: false
default_build_folder: .dacecache
experimental:
  check_race_conditions: false
  validate_undefs: false
external_transformations_path: $HOME/dace_transformations/external_transformations
frontend:
  avoid_wcr: false
  cache_size: 32
  check_args: false
  dont_fuse_callbacks: false
  implicit_recursion_depth: 64
  preprocessing_passes: 5
  raise_nested_parsing_errors: false
  typed_callbacks_only: false
  unroll_threshold: -1
  verbose_errors: false
instrumentation:
  papi:
    default_counters: '[''PAPI_TOT_INS'', ''PAPI_TOT_CYC'', ''PAPI_L2_TCM'', ''PAPI_L3_TCM'']'
    overhead_compensation: true
    vectorization_analysis: false
  report_each_invocation: true
library:
  blas:
    default_implementation: pure
    override: false
  lapack:
    default_implementation: OpenBLAS
    override: false
  linalg:
    default_implementation: OpenBLAS
    override: false
  pblas:
    default_implementation: MKLMPICH
    override: false
optimizer:
  automatic_simplification: true
  autooptimize: false
  autospecialize: false
  autotile_partial_parallelism: true
  autotile_size: 128
  detect_control_flow: true
  match_exception: false
  save_intermediate: false
  symbolic_positive: true
  visualize_sdfv: false
profiling: false
profiling_status: true
progress: true
store_history: true
testing:
  deserialize_exception: false
  serialization: false
  serialize_all_fields: false
treps: 100
